apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-example

resources:
- deploy.yaml
- service.yaml
- otel-collector.yaml
- argocd-slack.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-github-notifications
    literals:
      - notifications=app-deploy-success,app-deploy-failed
      - useAppName=false
    options:
      labels:
        liatr.io/notifications: ghwehook
