---
name: PR Linter

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  triage:
    uses: liatrio/tag-o11y-github-actions/.github/workflows/pr-conventional.yaml@e856558de058a68804047a6ce67d176b69412729
    secrets: inherit
